export const categories = [
  { id: 'student', name: 'Student / Academic', slug: 'student' },
  { id: 'engineering', name: 'Engineering / Electronics', slug: 'engineering' },
  { id: 'math', name: 'Math / Science', slug: 'math' },
  { id: 'developer', name: 'Developer Tools', slug: 'developer' },
  { id: 'text', name: 'Text Tools', slug: 'text' },
  { id: 'file', name: 'File / Image Tools', slug: 'file' },
  { id: 'converters', name: 'Converters', slug: 'converters' },
  { id: 'everyday', name: 'Everyday / Productivity', slug: 'everyday' }
];

export const tools = [
  // Student Tools
  { id: 1, slug: 'cgpa-calculator', name: 'CGPA Calculator', category: 'student', desc: 'Calculate CGPA using semester-wise GPA and credits.' },
  { id: 2, slug: 'gpa-calculator', name: 'GPA Calculator', category: 'student', desc: 'Calculate your semester GPA based on subject grades and credits.' },
  { id: 3, slug: 'percentage-calculator', name: 'Percentage Calculator', category: 'student', desc: 'Calculate percentage of numbers, increase, decrease, and differences.' },
  { id: 4, slug: 'attendance-calculator', name: 'Attendance Calculator', category: 'student', desc: 'Check current attendance and calculate classes required to reach a target.' },
  { id: 5, slug: 'bunk-calculator', name: 'Bunk Calculator', category: 'student', desc: 'Calculate how many classes you can skip while maintaining a target percentage.' },
  { id: 6, slug: 'required-attendance-calculator', name: 'Required Attendance Calculator', category: 'student', desc: 'Calculate classes needed to hit a specific attendance percentage.' },
  { id: 7, slug: 'exam-countdown', name: 'Exam Countdown', category: 'student', desc: 'Live countdown timer to your upcoming exams.' },
  { id: 8, slug: 'study-timer', name: 'Study Timer', category: 'student', desc: 'Pomodoro timer to help you focus during study sessions.' },
  { id: 9, slug: 'semester-planner', name: 'Semester Planner', category: 'student', desc: 'Plan subjects, deadlines, and priorities.' },
  { id: 10, slug: 'grade-calculator', name: 'Grade Calculator', category: 'student', desc: 'Calculate current grade and required final exam score.' },
  { id: 11, slug: 'marks-percentage-calculator', name: 'Marks Percentage Calculator', category: 'student', desc: 'Convert marks to percentages instantly.' },
  { id: 12, slug: 'sgpa-calculator', name: 'SGPA Calculator', category: 'student', desc: 'Calculate your SGPA for the current semester.' },
  { id: 13, slug: 'cgpa-to-percentage', name: 'CGPA to Percentage', category: 'student', desc: 'Convert your CGPA to a percentage.' },
  { id: 14, slug: 'percentage-to-cgpa', name: 'Percentage to CGPA', category: 'student', desc: 'Convert percentage back to a CGPA.' },
  { id: 15, slug: 'age-calculator', name: 'Age Calculator', category: 'student', desc: 'Calculate your exact age in years, months, and days.' },

  // Engineering Tools
  { id: 16, slug: 'ohms-law-calculator', name: "Ohm's Law Calculator", category: 'engineering', desc: 'Calculate voltage, current, resistance and power.' },
  { id: 17, slug: 'resistor-calculator', name: 'Resistor Calculator', category: 'engineering', desc: 'Calculate resistance from voltage and current.' },
  { id: 18, slug: 'resistor-color-code', name: 'Resistor Color Code Calculator', category: 'engineering', desc: 'Decode 4-band, 5-band, and 6-band resistors.' },
  { id: 19, slug: 'series-resistor-calculator', name: 'Series Resistor Calculator', category: 'engineering', desc: 'Calculate equivalent resistance for resistors in series.' },
  { id: 20, slug: 'parallel-resistor-calculator', name: 'Parallel Resistor Calculator', category: 'engineering', desc: 'Calculate equivalent resistance for resistors in parallel.' },
  { id: 21, slug: 'voltage-divider-calculator', name: 'Voltage Divider Calculator', category: 'engineering', desc: 'Calculate output voltage of a resistive divider.' },
  { id: 22, slug: 'current-divider-calculator', name: 'Current Divider Calculator', category: 'engineering', desc: 'Calculate current through parallel branches.' },
  { id: 23, slug: 'led-resistor-calculator', name: 'LED Resistor Calculator', category: 'engineering', desc: 'Find the correct resistor for an LED circuit.' },
  { id: 24, slug: 'power-calculator', name: 'Power Calculator', category: 'engineering', desc: 'Calculate electrical power using V, I, and R.' },
  { id: 25, slug: 'capacitor-calculator', name: 'Capacitor Calculator', category: 'engineering', desc: 'Calculate charge, voltage, and capacitance.' },
  { id: 26, slug: 'capacitor-series-calculator', name: 'Capacitor Series Calculator', category: 'engineering', desc: 'Calculate equivalent capacitance in series.' },
  { id: 27, slug: 'capacitor-parallel-calculator', name: 'Capacitor Parallel Calculator', category: 'engineering', desc: 'Calculate equivalent capacitance in parallel.' },
  { id: 28, slug: 'rc-time-constant', name: 'RC Time Constant Calculator', category: 'engineering', desc: 'Calculate time constant of an RC circuit.' },
  { id: 29, slug: 'rl-time-constant', name: 'RL Time Constant Calculator', category: 'engineering', desc: 'Calculate time constant of an RL circuit.' },
  { id: 30, slug: 'resonant-frequency', name: 'Resonant Frequency Calculator', category: 'engineering', desc: 'Calculate resonance frequency of an LC/RLC circuit.' },
  { id: 31, slug: 'frequency-period', name: 'Frequency to Period Calculator', category: 'engineering', desc: 'Convert frequency to time period.' },
  { id: 32, slug: 'period-frequency', name: 'Period to Frequency Calculator', category: 'engineering', desc: 'Convert time period to frequency.' },
  { id: 33, slug: 'decibel-calculator', name: 'Decibel Calculator', category: 'engineering', desc: 'Calculate decibels for power, voltage, and current ratios.' },
  { id: 34, slug: 'adc-resolution', name: 'ADC Resolution Calculator', category: 'engineering', desc: 'Calculate steps and voltage resolution of an ADC.' },
  { id: 35, slug: 'dac-resolution', name: 'DAC Resolution Calculator', category: 'engineering', desc: 'Calculate DAC resolution and steps.' },
  { id: 36, slug: 'pwm-calculator', name: 'PWM Calculator', category: 'engineering', desc: 'Calculate duty cycle, period, and frequency of a PWM signal.' },
  { id: 37, slug: 'transformer-calculator', name: 'Transformer Calculator', category: 'engineering', desc: 'Calculate voltage and turns ratio of a transformer.' },
  { id: 38, slug: 'battery-runtime', name: 'Battery Runtime Calculator', category: 'engineering', desc: 'Estimate battery life based on capacity and load.' },
  { id: 39, slug: 'opamp-calculator', name: 'Op-Amp Calculator', category: 'engineering', desc: 'Calculate gain and output of inverting and non-inverting op-amps.' },
  { id: 40, slug: 'electrical-unit-converter', name: 'Electrical Unit Converter', category: 'engineering', desc: 'Convert between standard electrical units.' },

  // Math / Science
  { id: 41, slug: 'scientific-calculator', name: 'Scientific Calculator', category: 'math', desc: 'Advanced browser-based scientific calculator.' },
  { id: 42, slug: 'fraction-calculator', name: 'Fraction Calculator', category: 'math', desc: 'Add, subtract, multiply, and divide fractions.' },
  { id: 43, slug: 'ratio-calculator', name: 'Ratio Calculator', category: 'math', desc: 'Simplify and solve ratios.' },
  { id: 44, slug: 'average-calculator', name: 'Average Calculator', category: 'math', desc: 'Calculate mean, median, and mode.' },
  { id: 45, slug: 'standard-deviation', name: 'Standard Deviation Calculator', category: 'math', desc: 'Calculate population and sample standard deviation.' },
  { id: 46, slug: 'variance-calculator', name: 'Variance Calculator', category: 'math', desc: 'Calculate statistical variance.' },
  { id: 47, slug: 'quadratic-equation', name: 'Quadratic Equation Solver', category: 'math', desc: 'Solve quadratic equations easily.' },
  { id: 48, slug: 'simple-interest', name: 'Simple Interest Calculator', category: 'math', desc: 'Calculate simple interest.' },
  { id: 49, slug: 'compound-interest', name: 'Compound Interest Calculator', category: 'math', desc: 'Calculate compound interest.' },
  { id: 50, slug: 'emi-calculator', name: 'EMI Calculator', category: 'math', desc: 'Calculate equated monthly installments for loans.' },

  // Developer Tools
  { id: 51, slug: 'json-formatter', name: 'JSON Formatter', category: 'developer', desc: 'Format and minify JSON strings.' },
  { id: 52, slug: 'json-validator', name: 'JSON Validator', category: 'developer', desc: 'Validate JSON and find syntax errors.' },
  { id: 53, slug: 'json-to-csv', name: 'JSON to CSV Converter', category: 'developer', desc: 'Convert JSON arrays to CSV format.' },
  { id: 54, slug: 'csv-to-json', name: 'CSV to JSON Converter', category: 'developer', desc: 'Convert CSV data to JSON format.' },
  { id: 55, slug: 'base64-encoder', name: 'Base64 Encoder', category: 'developer', desc: 'Encode text to Base64.' },
  { id: 56, slug: 'base64-decoder', name: 'Base64 Decoder', category: 'developer', desc: 'Decode Base64 to text.' },
  { id: 57, slug: 'url-encoder', name: 'URL Encoder', category: 'developer', desc: 'Encode text for URLs.' },
  { id: 58, slug: 'url-decoder', name: 'URL Decoder', category: 'developer', desc: 'Decode URL-encoded text.' },
  { id: 59, slug: 'jwt-decoder', name: 'JWT Decoder', category: 'developer', desc: 'Decode JSON Web Tokens locally.' },
  { id: 60, slug: 'uuid-generator', name: 'UUID Generator', category: 'developer', desc: 'Generate random UUIDs securely.' },
  { id: 61, slug: 'password-generator', name: 'Password Generator', category: 'developer', desc: 'Generate strong, secure passwords.' },
  { id: 62, slug: 'hash-generator', name: 'Hash Generator', category: 'developer', desc: 'Generate SHA-256 and other cryptographic hashes.' },
  { id: 63, slug: 'timestamp-converter', name: 'Timestamp Converter', category: 'developer', desc: 'Convert Unix timestamps to human-readable dates.' },
  { id: 64, slug: 'regex-tester', name: 'Regex Tester', category: 'developer', desc: 'Test regular expressions against strings.' },
  { id: 65, slug: 'html-encoder', name: 'HTML Encoder / Decoder', category: 'developer', desc: 'Encode and decode HTML entities.' },
  { id: 66, slug: 'markdown-preview', name: 'Markdown Previewer', category: 'developer', desc: 'Preview and test markdown locally.' },
  { id: 67, slug: 'color-converter', name: 'Color Converter', category: 'developer', desc: 'Convert between HEX, RGB, and HSL.' },
  { id: 68, slug: 'css-minifier', name: 'CSS Minifier', category: 'developer', desc: 'Minify CSS code locally.' },
  { id: 69, slug: 'javascript-minifier', name: 'JavaScript Minifier', category: 'developer', desc: 'Minify JavaScript code locally.' },
  { id: 70, slug: 'sql-formatter', name: 'SQL Formatter', category: 'developer', desc: 'Format SQL queries.' },

  // Text Tools
  { id: 71, slug: 'word-counter', name: 'Word Counter', category: 'text', desc: 'Count words, characters, and sentences.' },
  { id: 72, slug: 'character-counter', name: 'Character Counter', category: 'text', desc: 'Count characters with and without spaces.' },
  { id: 73, slug: 'case-converter', name: 'Case Converter', category: 'text', desc: 'Convert text case (UPPER, lower, Title, etc).' },
  { id: 74, slug: 'remove-duplicate-lines', name: 'Duplicate Line Remover', category: 'text', desc: 'Remove duplicate lines from text.' },
  { id: 75, slug: 'text-sorter', name: 'Text Sorter', category: 'text', desc: 'Sort lines alphabetically or by length.' },
  { id: 76, slug: 'text-cleaner', name: 'Text Cleaner', category: 'text', desc: 'Remove extra spaces and empty lines.' },
  { id: 77, slug: 'find-replace', name: 'Find and Replace', category: 'text', desc: 'Find and replace text efficiently.' },
  { id: 78, slug: 'text-reverser', name: 'Text Reverser', category: 'text', desc: 'Reverse lines or characters.' },
  { id: 79, slug: 'lorem-ipsum', name: 'Lorem Ipsum Generator', category: 'text', desc: 'Generate placeholder text.' },
  { id: 80, slug: 'reading-time', name: 'Reading Time Calculator', category: 'text', desc: 'Calculate estimated reading time.' },

  // File / Image Tools
  { id: 81, slug: 'image-compressor', name: 'Image Compressor', category: 'file', desc: 'Compress JPG and PNG images locally in browser.' },
  { id: 82, slug: 'image-resizer', name: 'Image Resizer', category: 'file', desc: 'Resize images securely.' },
  { id: 83, slug: 'image-cropper', name: 'Image Cropper', category: 'file', desc: 'Crop images using browser canvas.' },
  { id: 84, slug: 'image-converter', name: 'Image Format Converter', category: 'file', desc: 'Convert images to WebP, PNG, or JPG.' },
  { id: 85, slug: 'image-to-base64', name: 'Image to Base64', category: 'file', desc: 'Convert image files to Base64 strings.' },
  { id: 86, slug: 'file-size-converter', name: 'File Size Converter', category: 'file', desc: 'Convert bytes to KB, MB, GB.' },
  { id: 87, slug: 'text-file-generator', name: 'Text File Generator', category: 'file', desc: 'Create and download text files.' },
  { id: 88, slug: 'csv-generator', name: 'CSV Generator', category: 'file', desc: 'Generate dummy CSV files.' },

  // Converters
  { id: 89, slug: 'length-converter', name: 'Length Converter', category: 'converters', desc: 'Convert meters, inches, miles, etc.' },
  { id: 90, slug: 'weight-converter', name: 'Weight Converter', category: 'converters', desc: 'Convert kg, pounds, ounces, etc.' },
  { id: 91, slug: 'temperature-converter', name: 'Temperature Converter', category: 'converters', desc: 'Convert Celsius, Fahrenheit, Kelvin.' },
  { id: 92, slug: 'area-converter', name: 'Area Converter', category: 'converters', desc: 'Convert square meters, acres, etc.' },
  { id: 93, slug: 'volume-converter', name: 'Volume Converter', category: 'converters', desc: 'Convert liters, gallons, etc.' },
  { id: 94, slug: 'speed-converter', name: 'Speed Converter', category: 'converters', desc: 'Convert km/h, mph, m/s, etc.' },
  { id: 95, slug: 'time-converter', name: 'Time Converter', category: 'converters', desc: 'Convert seconds, minutes, hours, days.' },

  // Everyday / Productivity
  { id: 96, slug: 'date-difference', name: 'Date Difference Calculator', category: 'everyday', desc: 'Calculate the exact difference between dates.' },
  { id: 97, slug: 'days-between-dates', name: 'Days Between Dates', category: 'everyday', desc: 'Calculate days between two dates.' },
  { id: 98, slug: 'countdown-timer', name: 'Countdown Timer', category: 'everyday', desc: 'Simple countdown timer utility.' },
  { id: 99, slug: 'stopwatch', name: 'Stopwatch', category: 'everyday', desc: 'Browser-based stopwatch with lap functionality.' },
  { id: 100, slug: 'random-number-generator', name: 'Random Number Generator', category: 'everyday', desc: 'Generate random numbers securely.' },
];
